export enum VatRateType {
  STANDARD = "STANDARD",
  EXEMPT = "EXEMPT",
  NOT_TAXED = "NOT_TAXED",
}

export enum Status {
  DRAFT = "DRAFT",
  PENDING = "PENDING",
  PAID = "PAID",
  OVERDUE = "OVERDUE",
  CANCELLED = "CANCELLED",
  PARTIALLY_PAID = "PARTIALLY_PAID",
}
